### PR TITLE
Lazy Loading Components: fix react-highlight not working with react 16

### PR DESCRIPTION
**Pull request by nekitk**
Fixes https://github.com/arunoda/learnnextjs-demo/issues/18, https://github.com/arunoda/learnnextjs-content/issues/75, https://github.com/arunoda/learnnextjs-content/issues/63

### CODE REVIEW

**Comment by yhirano55** [comment]
Nice work 👍

**Comment by F1LT3R** [comment]
This is not merged yet? I just ran into the same error and found the same fix.

**Comment by danjrichardson** [comment]
@arunoda would be good to have this change merged as it's a stumbling block currently when working through the examples. This version bump fixes the problem

**Comment by timneutkens** [comment]
https://github.com/arunoda/learnnextjs-demo/pull/35

**Pull request closed without merging**
